"""karma

Revision ID: 43f3af4943f
Revises: ff9383f37e
Create Date: 2015-10-18 01:18:45.996317

"""

# revision identifiers, used by Alembic.
revision = '43f3af4943f'
down_revision = 'ff9383f37e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('karma_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('from_id', sa.Integer(), nullable=False),
        sa.Column('to_id', sa.Integer(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=False),
        sa.Column('value', sa.Integer(), server_default='0', nullable=False),
        sa.ForeignKeyConstraint(['from_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['to_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_karma_records_from_id'), 'karma_records', ['from_id'], unique=False)
    op.create_index(op.f('ix_karma_records_project_id'), 'karma_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_karma_records_to_id'), 'karma_records', ['to_id'], unique=False)
    op.add_column('project_members', sa.Column('karma', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('projects', 'type',
               existing_type=postgresql.ENUM('tree', 'list', 'stickers', 'bubbles', name='project_type'),
               type_=postgresql.ENUM('tree', 'list', name='project_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'tree'::project_type"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'type',
               existing_type=postgresql.ENUM('tree', 'list', name='project_type'),
               type_=postgresql.ENUM('tree', 'list', 'stickers', 'bubbles', name='project_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'tree'::project_type"))
    op.drop_column('project_members', 'karma')
    op.drop_index(op.f('ix_karma_records_to_id'), table_name='karma_records')
    op.drop_index(op.f('ix_karma_records_project_id'), table_name='karma_records')
    op.drop_index(op.f('ix_karma_records_from_id'), table_name='karma_records')
    op.drop_table('karma_records')
    ### end Alembic commands ###
