"""sprint sort

Revision ID: 3fd4f49118e
Revises: 4756630dcf9
Create Date: 2015-12-09 17:21:09.345660

"""

# revision identifiers, used by Alembic.
revision = '3fd4f49118e'
down_revision = '4756630dcf9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('sort', sa.SmallInteger(), server_default='0', nullable=False))
    op.drop_column('sprints', 'finish')
    op.drop_column('sprints', 'start')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('start', sa.DATE(), server_default=sa.text("('now'::text)::date"), autoincrement=False, nullable=False))
    op.add_column('sprints', sa.Column('finish', sa.DATE(), server_default=sa.text("(('now'::text)::date + 7)"), autoincrement=False, nullable=False))
    op.drop_column('sprints', 'sort')
    ### end Alembic commands ###
