"""mp smallint->int

Revision ID: 3a69f7d1cce
Revises: 2c4d0d8d575
Create Date: 2015-05-20 10:00:07.991587

"""

# revision identifiers, used by Alembic.
revision = '3a69f7d1cce'
down_revision = '2c4d0d8d575'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE tasks ALTER COLUMN mp TYPE int[]")
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE tasks ALTER COLUMN mp TYPE smallint[]")
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    ### end Alembic commands ###
