"""tasks

Revision ID: 2c4d0d8d575
Revises: 4f37f0a4a80
Create Date: 2015-05-17 15:07:26.685265

"""

# revision identifiers, used by Alembic.
revision = '2c4d0d8d575'
down_revision = '4f37f0a4a80'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('assigned_id', sa.Integer(), nullable=True),
        sa.Column('mp', postgresql.ARRAY(sa.SmallInteger(), zero_indexes=True), nullable=True),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('status', postgresql.ENUM('open', 'progress', 'pause', 'review', 'done', 'canceled', name='task_status'), nullable=False),
        sa.Column('subject', sa.String(length=1024), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['assigned_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_table('tasks')
    ### end Alembic commands ###
