"""projects.type

Revision ID: 51a9dd090d7
Revises: f4e4aecaf5
Create Date: 2015-06-08 22:53:56.233864

"""

# revision identifiers, used by Alembic.
revision = '51a9dd090d7'
down_revision = 'f4e4aecaf5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE project_type AS ENUM('tree', 'list', 'stickers', 'bubbles')")
    op.execute("ALTER TABLE projects ADD type project_type NOT NULL default 'tree'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'type')
    ### end Alembic commands ###
