"""history importance, character

Revision ID: 5998315b99a
Revises: 4ce61c1f756
Create Date: 2015-07-11 14:58:36.675040

"""

# revision identifiers, used by Alembic.
revision = '5998315b99a'
down_revision = '4ce61c1f756'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_history', sa.Column('character', sa.SmallInteger(), nullable=True))
    op.add_column('task_history', sa.Column('importance', sa.SmallInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_history', 'importance')
    op.drop_column('task_history', 'character')
    ### end Alembic commands ###
