"""Project description + archived flag

Revision ID: 4756630dcf9
Revises: 49f3ca0cde8
Create Date: 2015-11-18 22:57:52.357409

"""

# revision identifiers, used by Alembic.
revision = '4756630dcf9'
down_revision = '49f3ca0cde8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('archived', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('projects', sa.Column('intro', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'intro')
    op.drop_column('project_members', 'archived')
    ### end Alembic commands ###
