"""importance, character

Revision ID: f4e4aecaf5
Revises: 1e41b1b4d
Create Date: 2015-05-30 10:45:48.320396

"""

# revision identifiers, used by Alembic.
revision = 'f4e4aecaf5'
down_revision = '1e41b1b4d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('character', sa.SmallInteger(), nullable=True))
    op.add_column('tasks', sa.Column('importance', sa.SmallInteger(), server_default='0', nullable=False))
    ### end Alembic commands ###alembic


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'importance')
    op.drop_column('tasks', 'character')
    ### end Alembic commands ###
