"""task_history

Revision ID: 1e41b1b4d
Revises: 3a69f7d1cce
Create Date: 2015-05-23 20:20:04.757307

"""

# revision identifiers, used by Alembic.
revision = '1e41b1b4d'
down_revision = '3a69f7d1cce'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

task_status = postgresql.ENUM('open', 'progress', 'pause', 'review', 'done', 'canceled', name='task_status', create_type=False)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('assigned_id', sa.Integer(), nullable=True),
        sa.Column('status', task_status, nullable=True),
        sa.Column('subject', sa.String(length=1024), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['assigned_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_history_task_id'), 'task_history', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_history_user_id'), 'task_history', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_history_user_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_task_id'), table_name='task_history')
    op.drop_table('task_history')
    ### end Alembic commands ###
