"""task estimate time

Revision ID: 3a1c57b2997
Revises: 31c3d0017ef
Create Date: 2016-06-29 09:21:20.672609

"""

# revision identifiers, used by Alembic.
revision = '3a1c57b2997'
down_revision = '31c3d0017ef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimate', sa.DECIMAL(precision=3, scale=1), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'estimate')
    ### end Alembic commands ###
