"""password reset

Revision ID: 31c3d0017ef
Revises: 12dad8cfdd0
Create Date: 2016-06-08 16:55:49.403636

"""

# revision identifiers, used by Alembic.
revision = '31c3d0017ef'
down_revision = '12dad8cfdd0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.alter_column('projects', 'type',
               existing_type=postgresql.ENUM('tree', 'list', 'stickers', 'bubbles', name='project_type'),
               type_=postgresql.ENUM('tree', 'list', name='project_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'tree'::project_type"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'type',
               existing_type=postgresql.ENUM('tree', 'list', name='project_type'),
               type_=postgresql.ENUM('tree', 'list', 'stickers', 'bubbles', name='project_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'tree'::project_type"))
    op.drop_table('password_reset_tokens')
    ### end Alembic commands ###
