"""project access

Revision ID: d36d74f8f516
Revises: 3a1c57b2997
Create Date: 2016-10-30 18:57:32.465545

"""

# revision identifiers, used by Alembic.
revision = 'd36d74f8f516'
down_revision = '3a1c57b2997'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE access_level AS ENUM('owner', 'lead', 'developer', 'watcher', 'bylink', 'any')")
    op.add_column('projects', sa.Column('ac_link_code', sa.String(length=64), nullable=True))
    op.add_column('projects', sa.Column('ac_read', postgresql.ENUM('owner', 'lead', 'developer', 'watcher', 'bylink', 'any', name='access_level'), server_default='watcher', nullable=False))
    op.add_column('projects', sa.Column('ac_comment', postgresql.ENUM('owner', 'lead', 'developer', 'watcher', 'bylink', 'any', name='access_level'), server_default='watcher', nullable=False))
    op.create_index(op.f('ix_projects_ac_link_code'), 'projects', ['ac_link_code'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_ac_link_code'), table_name='projects')
    op.drop_column('projects', 'ac_comment')
    op.drop_column('projects', 'ac_read')
    op.drop_column('projects', 'ac_link_code')
    op.execute('DROP TYPE access_level')
    ### end Alembic commands ###
