"""bugs

Revision ID: 91de6516b2db
Revises: d36d74f8f516
Create Date: 2018-02-15 17:43:24.718276

"""

# revision identifiers, used by Alembic.
revision = '91de6516b2db'
down_revision = 'd36d74f8f516'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'progress', 'pause', 'test', 'fixed', 'canceled', name='bug_status'), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bugs_task_id'), 'bugs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bugs_task_id'), table_name='bugs')
    op.drop_table('bugs')
    op.execute('DROP TYPE bug_status')
    # ### end Alembic commands ###
