"""sprint.description

Revision ID: eae4261462f3
Revises: 91de6516b2db
Create Date: 2020-06-02 00:47:27.821890

"""

# revision identifiers, used by Alembic.
revision = 'eae4261462f3'
down_revision = '91de6516b2db'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sprints', 'description')
    # ### end Alembic commands ###
