"""tasks.soundtrack

Revision ID: cdef380a0c8a
Revises: 864c9968968a
Create Date: 2022-09-18 16:43:33.338456

"""

# revision identifiers, used by Alembic.
revision = 'cdef380a0c8a'
down_revision = '864c9968968a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('soundtrack', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'soundtrack')
    # ### end Alembic commands ###
