"""tasks.top_id

Revision ID: 89a60f0e0fe1
Revises: 1ed92940fcd5
Create Date: 2022-09-14 00:27:18.558940

"""

# revision identifiers, used by Alembic.
revision = '89a60f0e0fe1'
down_revision = '1ed92940fcd5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

Session = sessionmaker()


def upgrade():
    bind = op.get_bind()
    sess = Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('top_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_top_id'), 'tasks', ['top_id'], unique=False)

    # Считаем top_id для каждой подзадачи. Туповато, но для миграции сойдёт.
    q = sess.execute("SELECT * FROM tasks WHERE parent_id IS NOT NULL")
    for task in q:
        top = next(sess.execute("""
            WITH RECURSIVE r AS (
                SELECT id, parent_id FROM tasks WHERE id = :task_id
                UNION
                SELECT tasks.id, tasks.parent_id
                FROM tasks JOIN r ON r.parent_id = tasks.id
            ) SELECT * FROM r WHERE parent_id IS NULL;
        """, {'task_id': task['id']}))
        sess.execute("UPDATE tasks SET top_id = :top_id WHERE id = :task_id", {'task_id': task['id'], 'top_id': top['id']})

    op.create_foreign_key(None, 'tasks', 'tasks', ['top_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_top_id'), table_name='tasks')
    op.drop_column('tasks', 'top_id')
    # ### end Alembic commands ###
